alumni_bckend/alumni_backend/urls.py
from django.contrib import admin
from django.urls import path, include
#import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playground/', include('playground.urls')),
    #path("__debug__/", include("debug_toolbar.urls")),
]

alumni_bckend/playground/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('send_email/', views.send_email, name='send_email'),
    path('login/', views.login, name='login'),
    path('choose/',views.choose, name = 'choose'),
    path('alumni/', views.alumni_list, name='alumni_list'),
    path('alumni/create/', views.alumni_create, name='alumni_create'),
    path('alumni/update/', views.alumni_update, name='alumni_update'),
    path('alumni/delete-confirm/<str:first_name>/<str:last_name>', views.alumni_delete, name='alumni_delete'),
    path('alumni/delete/', views.delete_alumni, name='delete_alumni'),
    path('alumni/user_query/', views.query_form, name='query'),
    path('alumni/list_tables/', views.list_tables, name='list_tables'),
    path('alumni/view_table/<str:table_name>', views.view_table, name='view_table'),
    path('add_job_opening/', views.add_job_opening, name='add_job_opening'),
    path('delete_job_opening/<int:job_id>/', views.delete_job_opening, name='delete_job_opening'),
    path('job_openings/',views.job_openings,name='job_openings'),
    path('alumni_by_year/<int:graduation_year>/', views.alumni_by_graduation_year, name='alumni_by_year'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

alumni_bckend/playground/models.py
from django.db import models

class Alumni(models.Model):
    Alumni_ID = models.CharField(max_length=10, primary_key=True)
    First_name = models.CharField(max_length=10)
    Last_name = models.CharField(max_length=10, null=True)
    email = models.CharField(max_length=20, null=True)
    Address = models.CharField(max_length=20, null=True)
    Contact_No = models.BigIntegerField(null=True)
    minors = models.CharField(max_length=10, null=True)
    Batch_id = models.CharField(max_length=10, null=True)
    Position_id = models.CharField(max_length=10, null=True)
    Donation_id = models.CharField(max_length=10, null=True)

    def __str__(self):
        if self.Last_name:   
            return self.First_name + ' ' + self.Last_name
        else:
            return self.First_name
    class Meta:
        db_table = 'alumni'


class Work(models.Model):
    position_id = models.CharField(max_length=10)
    position_name = models.CharField(max_length=255)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return self.position_name
    

class JobOpening(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    application_deadline = models.DateField()
    alumni = models.ForeignKey(Alumni, on_delete=models.CASCADE)  # Add this field

    def __str__(self):
        return self.title
    
class User(models.Model):
    password = models.CharField(max_length=100)
    passkey = models.CharField(max_length=100)

alumni_bckend/playground/forms.py
from django import forms
from .models import Alumni
from .models import JobOpening
from .models import Work

class QueryForm(forms.Form):
    select_field = forms.CharField(label='SELECT', required=False)
    insert_field = forms.CharField(label='INSERT', required=False)
    update_field = forms.CharField(label='UPDATE', required=False)
    delete_field = forms.CharField(label='DELETE', required=False)

class UserInputForm(forms.Form):
    user_input = forms.CharField(
        label='Enter query:',
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 40}) 
    )

class NameForm(forms.Form):
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    subject = forms.CharField(max_length=200, label='Subject')
    message = forms.CharField(widget=forms.Textarea, label='Message')

class LoginForm(forms.Form):
    password = forms.CharField(label="SRN")
    passkey = forms.CharField(widget=forms.PasswordInput)

class AlumniForm(forms.ModelForm):
    class Meta:
        model = Alumni
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AlumniForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

class JobOpeningForm(forms.ModelForm):
    class Meta:
        model = JobOpening
        fields = ['title', 'description', 'application_deadline', 'alumni']

alumni_bckend/playground/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Alumni, Batch
from django.db import connection , ProgrammingError
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import NameForm
import re
from .forms import AlumniForm
from .models import JobOpening
from .forms import JobOpeningForm  
from django.utils import timezone
from .models import User
from .forms import LoginForm



def choose(request):
    return render(request, 'login_success.html')


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            passkey = form.cleaned_data['passkey']
            
            user = User.objects.filter(password=password, passkey=passkey).first()

            if user:
                request.session['user_password'] = password
                return redirect('http://127.0.0.1:8000/playground/choose/')
            else:
                return HttpResponse("Invalid User")
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def send_email(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = 'manoj2003r@gmail.com'  
            alumni = Alumni.objects.filter(First_name=first_name, Last_name=last_name).first()

            if alumni:
                recipient_email = alumni.email
                print(recipient_email)
                send_mail(subject, message, from_email, [recipient_email])
                return render(request, 'email_sent.html', {'email_sent': True})
            else:
                return render(request, 'email_sent.html', {'email_sent': False})

    else:
        form = NameForm()

    return render(request, 'email_form.html', {'form': form})

def success(request):
    return render(request, 'success.html')


def query_form(request):
    if request.method == 'POST':
        user_query = request.POST.get('user_query')
        action = request.POST.get('action')
        user_password = request.session.get('user_password')
        user_password = user_password[6:8]
        if int(user_password) > 22:
            forbidden_keywords = ['INSERT', 'UPDATE', 'DELETE']

            if any(keyword in user_query.upper() for keyword in forbidden_keywords):
                return HttpResponse("You are not allowed to perform this operation.")

        try:
            if action == 'execute':
                with connection.cursor() as cursor:
                    cursor.execute(user_query)
                    results = cursor.fetchall()
                return render(request, 'query_result.html', {'results': results})
            elif action == 'download':
                with connection.cursor() as cursor:
                    cursor.execute(user_query)
                    results = cursor.fetchall()
                    if results:
                        columns = [desc[0] for desc in cursor.description]
                        csv_data = "\n".join([",".join(map(str, row)) for row in results])
                    else:
                        return render(request, 'no_result.html')
                response = HttpResponse(content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename="query_result.csv"'
                response.write(f"{','.join(columns)}\n{csv_data}")
                return response
        except ProgrammingError as e:
            error_message = f"Syntax error in the query: {str(e)}"
            return HttpResponse(error_message)
    else:
        return render(request, 'query_form.html')


def alumni_list(request):
    alumni = Alumni.objects.all()
    return render(request, 'alumni_list.html', {'alumni': alumni})

def alumni_create(request):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
            
    if request.method == 'POST':
        form = AlumniForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('alumni_list')
    else:
        form = AlumniForm()
    return render(request, 'alumni_form.html', {'form': form})

def alumni_update(request):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
    if request.method == 'POST':
        alumni_id = request.POST['Alumni_ID']
        alumni = Alumni.objects.filter(Alumni_ID=alumni_id).first()
        if alumni:
            form = AlumniForm(request.POST, instance=alumni)
            if form.is_valid():
                form.save()
                return redirect('alumni_list')
        else:
            return HttpResponse("The Alumni does not exist.")

    else:
        form = AlumniForm()

    return render(request, 'alumni_update.html', {'form': form})


def alumni_delete(request,first_name,last_name):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
    if request.method == 'POST':
        alumni = Alumni.objects.filter(First_name=first_name, Last_name=last_name).first()
        if alumni:
            alumni.delete()
            return redirect('alumni_list')
        else:
            return HttpResponse("The Alumni does not exist.")
    return render(request, 'alumni_confirm_delete.html', {'first_name':first_name , 'last_name':last_name})

def delete_alumni(request):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        return redirect('alumni_delete',first_name,last_name)
    return render(request, 'delete_alumni.html')


def list_tables(request):
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES;")
        tables = [table[0] for table in cursor.fetchall()]
    table_names = ['alumni', 'batch', 'degree', 'donations', 'work', 'publications']

    return render(request, 'list_tables.html', {'tables': tables, 'table_names': table_names})

def view_table(request, table_name):
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT * FROM {table_name}")
        columns = [desc[0] for desc in cursor.description]
        data = cursor.fetchall()

    context = {
        'table_name': table_name,
        'columns': columns,
        'data': data,
    }

    return render(request, 'view_table.html', context)

def job_openings(request):
    current_date = timezone.now().date()  

    job_listings = JobOpening.objects.select_related('alumni').filter(application_deadline__gte=current_date)

    return render(request, 'job_opening.html', {'job_listings': job_listings})


def add_job_opening(request):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
    if request.method == 'POST':
        form = JobOpeningForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('job_openings')
    else:
        form = JobOpeningForm()
    
    return render(request, 'add_job_opening.html', {'form': form})

def delete_job_opening(request, job_id):
    user_password = request.session.get('user_password')
    user_password = user_password[6:8]
    if int(user_password) < 22:
        return HttpResponse("You are not allowed to perform this operation.")
    job = JobOpening.objects.get(pk=job_id)
    if request.method == 'POST':
        job.delete()
        return redirect('job_openings')
    
    return render(request, 'delete_job_opening.html', {'job': job})

def call_stored_procedure(p_graduation_year):
    with connection.cursor() as cursor:
        cursor.callproc('GetAlumniByGraduationYear', [p_graduation_year])
        results = cursor.fetchall()
    return results


def alumni_by_graduation_year(request, graduation_year):
    alumni_list = call_stored_procedure(graduation_year)
    context = {'alumni_list': alumni_list, 'graduation_year': graduation_year}
    return render(request, 'procedure.html', context)

alumni_bckend/playground/templates/add_job_opening.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Job Opening</title>
    <style>
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .form-container {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            width: 350px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #3498db;
            text-align: center;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        input[type="text"] {
            padding: 10px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            padding: 10px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
            height: 150px; 
            resize: horizontal;
        }

        button {
            background-color: #3498db;
            color: #fff;
            border: none;
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1>Add Job Opening</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Job Opening</button>
        </form>
    </div>
</body>
</html>

alumni_bckend/playground/templates/alumni_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirm Alumni Deletion</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 20px;
        }
        h1 {
            font-size: 24px;
        }
        p {
            font-size: 18px;
        }
        strong {
            font-weight: bold;
        }
        form {
            display: inline;
        }
        button {
            background-color: #ff0000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }
        button:hover {
            background-color: #cc0000;
        }
        a {
            display: inline-block;
            margin-top: 10px;
            text-decoration: none;
            color: #000;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Confirm Alumni Deletion</h1>

    <p>Are you sure you want to delete the alumni with the following details?</p>

    <p><strong>Alumni Name:</strong> {{ first_name }} {{ last_name }}</p>
    <!-- Include any other alumni details you want to display here -->

    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Deletion</button>
    </form>

    <a href="{% url 'alumni_list' %}">Cancel</a>
</body>
</html>

alumni_bckend/playground/templates/alumni_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Alumni Record</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
        }
        h1 {
            color: #007BFF;
        }
        form {
            width: 60%;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        input[type="text"], textarea {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        label {
            display: block;
            margin: 10px 0;
            font-weight: bold;
        }
        button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <h1>Add Alumni Record</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Record</button>
    </form>
</body>
</html>

alumni_bckend/playground/templates/alumni_update.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Alumni Information</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #f5f5f5;
            color: #333;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            font-size: 36px;
            margin: 20px 0;
            color: #2E86C1;
        }
        p {
            font-size: 24px;
            margin: 20px 0;
        }
        form {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 10px;
            display: inline-block;
            padding: 20px;
            text-align: left;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            margin-top: 10px;
            font-size: 18px;
            font-weight: bold;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            background-color: #2E86C1;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 15px 30px;
            font-size: 20px;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
        }
        button:hover {
            background-color: #186A9F;
        }
    </style>
</head>
<body>
    <h1>Update Alumni Information</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Alumni</button>
    </form>
</body>
</html>

alumni_bckend/playground/templates/email_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Send Email to Alumni</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(135deg, #f8f8f8, #e6e6e6);
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }

        .email-form {
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            padding: 30px;
            width: 350px;
            text-align: center;
        }

        h1 {
            color: #007BFF;
            margin: 0 0 20px;
            font-size: 24px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            color: #333;
            font-weight: bold;
            margin-bottom: 5px;
            font-size: 16px;
        }

        input[type="text"], textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
            background-color: #f7f7f7;
        }

        button[type="submit"] {
            background-color: #007BFF;
            color: #fff;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="email-form">
        <h1>Send Email to Alumni</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_first_name">First Name:</label>
                {{ form.first_name }}
            </div>
            <div class="form-group">
                <label for="id_last_name">Last Name:</label>
                {{ form.last_name }}
            </div>
            <div class="form-group">
                <label for="id_subject">Email Subject:</label>
                {{ form.subject }}
            </div>
            <div class="form-group">
                <label for="id_message">Email Message:</label>
                {{ form.message }}
            </div>
            <button type="submit">Send Email</button>
        </form>
    </div>
</body>
</html>

alumni_bckend/playground/templates/email_sent.html
<!DOCTYPE html>
<html>
<head>
    <title>Email Sent</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(135deg, #00a6ff, #0072ff);
            color: #fff;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        h1 {
            font-size: 36px;
            margin: 0 0 20px;
            animation: bounce 1.5s infinite;
        }

        p {
            font-size: 20px;
        }

        a {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #ff5500;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            font-size: 18px;
            transition: background-color 0.3s;
        }

        a:hover {
            background-color: #e64500;
        }

        @keyframes bounce {
            0%, 20%, 50%, 80%, 100% {
                transform: translateY(0);
            }
            40% {
                transform: translateY(-20px);
            }
            60% {
                transform: translateY(-10px);
            }
        }
    </style>
</head>
<body>
    {% if email_sent and alumni %}
    <h1>Email Sent</h1>
    <p>Email sent successfully to {{ alumni.name }}.</p>
    {% else %}
    <h1>Email not Sent</h1>
    <p>Alumni not found. Email not sent.</p>
    {% endif %}
    <a href="{% url 'send_email' %}">Go back</a>
</body>
</html>

alumni_bckend/playground/templates/hello.html
<html>
    <body>
        {% if name %}
        <h1>hello {{name}}</h1>
        {% else %}
        <h1>hello world</h1>
        {% endif %}
    </body>
</html>


alumni_bckend/playground/templates/procedure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumni List</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: #f0f0f0;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            font-size: 2.5em;
            margin: 20px 0;
            color: #3498db;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        li {
            margin: 10px 0;
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease-in-out;
        }

        li:hover {
            transform: scale(1.05);
        }
    </style>
</head>
<body>
    <h1>Alumni List for Graduation Year {{ graduation_year }}</h1>
    <ul>
        {% for alumni in alumni_list %}
            <li>{{ alumni.1 }} {{ alumni.2 }} - {{ alumni.3 }}</li>
        {% endfor %}
    </ul>
</body>
</html>

alumni_bckend/playground/templates/query_form.html
<!DOCTYPE html>
<html>
<head>
    <title>SQL Query Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F5F5F5;
            text-align: center;
        }
        h1 {
            color: #3498DB;
        }
        form {
            max-width: 500px;
            margin: 0 auto;
            background: #ffffff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 15px 0px #ccc;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #333;
        }
        textarea {
            width: 100%;
            height: 200px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        button {
            background: #3498DB;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background: #267bb7;
        }
    </style>
</head>
<body>
    <h1>SQL Query Form</h1>
    <form method="post">
        {% csrf_token %}
        <label for="user_query">Enter your SQL query:</label>
        <textarea name="user_query" rows="10"></textarea>
        <br>
        <button type="submit" name="action" value="execute">Execute Query</button>
        <button type="submit" name="action" value="download">Download CSV</button>
    </form>
</body>
</html>

alumni_bckend/playground/templates/query_form2.html
<!DOCTYPE html>
<html>
<head>
    <title>SQL Query Builder</title>
    <style>
        /* Your CSS styles here */
    </style>
</head>
<body>
    <h1>SQL Query Builder</h1>
    <form method="post">
        {% csrf_token %}
        <label for="crud_operation">Select CRUD Operation:</label>
        <select name="crud_operation">
            <option value="SELECT">SELECT</option>
            <option value="INSERT">INSERT</option>
            <option value="UPDATE">UPDATE</option>
            <option value="DELETE">DELETE</option>
        </select>

        <label for="table_name">Table Name:</label>
        <input type="text" name="table_name" required>

        <label for="column_names">Column Names (comma-separated):</label>
        <input type="text" name="column_names" required>

        <label for="conditions">Conditions:</label>
        <textarea name="conditions" rows="5"></textarea>

        <button type="submit">Build and Execute Query</button>
    </form>
</body>
</html>

alumni_bckend/playground/templates/query_result.html
<!DOCTYPE html>
<html>
<head>
    <title>Query Result</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }
        h1 {
            color: #3498DB;
        }
        pre {
            background: #f5f5f5;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .table-container {
            width: 80%;
            margin: 20px auto;
            overflow-x: auto; /* Add horizontal scrollbar if needed */
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            padding: 10px 15px;
            text-align: center;
        }
        th {
            background-color: #3498DB;
            color: #fff;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #22b42e;
            color: #fff;
        }
    </style>
</head>
<body>
    <h1>Query Result</h1>

    <h2>Results:</h2>
    <div class="table-container">
        <table border="1">
            <thead>
                <tr>
                    {% for column_name in column_names %}
                        <th>{{ column_name }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for result in results %}
                    <tr>
                        {% for value in result %}
                            <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

alumni_bckend/playground/templates/success.html
<html><h1>Success!!</h1></html>

alumni_bckend/playground/templates/test.html
<table border="1">
    <tr>
        <th>Alumni ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Address</th>
        <th>Contact Number</th>
        <th>Minors</th>
        <th>Batch ID</th>
        <th>Position ID</th>
        <th>Donation ID</th>
    </tr>
    {% for alum in data %}
    <tr>
        <td>{{ alum.Alumni_ID }}</td>
        <td>{{ alum.First_name }}</td>
        <td>{{ alum.Last_name }}</td>
        <td>{{ alum.Email }}</td>
        <td>{{ alum.Address }}</td>
        <td>{{ alum.Contact_No }}</td>
        <td>{{ alum.minors }}</td>
        <td>{{ alum.Batch_id }}</td>
        <td>{{ alum.Position_id }}</td>
        <td>{{ alum.Donation_id }}</td>
    </tr>
    {% endfor %}
</table>